#!/bin/bash



mkdir -p pokemon_data

POKEMON_LIST="bulbasaur ivysaur venusaur charmander charmeleon"


for name in $POKEMON_LIST; do

    
    echo "Fetching data for $name..."

    
    URL="https://pokeapi.co/api/v2/pokemon/$name"
    FILENAME="pokemon_data/$name.json"

    if curl -f -s "$URL" -o "$FILENAME"; then
       
        echo "Saved data to $FILENAME ✅"
    else
       
        echo "Failed to retrieve data for $name ❌" >> errors.txt
    fi

    
    sleep 1


done

echo "Batch processing complete!"
